version: '3'
services:
  server:
    command: /bin/bash ./bin/prod.sh
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        buildno: 1
    container_name: got_server
    env_file: .env
    volumes:
      - ./server:/app
      - ./logs/gunicorn:/var/log/gunicorn
      - ./frontend/dist:/app/app/static/dist
    expose:
      - "8800"
    depends_on:
      - db
    ports:
      - "8840:8840"
    restart: always
  db:
    image: postgres:11.0
    container_name: got_db
    restart: always
    expose:
      - "5439"
    env_file: .env
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  nginx:
    container_name: got_nginx
    restart: always
    build:
      context: ./nginx/
      dockerfile: Dockerfile
    ports:
      - "4000:80"
#      - "443:443"
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./nginx/conf:/etc/nginx/conf
      - ./nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./server:/app
