# Generated by Django 2.0.7 on 2019-04-24 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_death',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='character',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='character', to='app.Character', verbose_name='Персонаж'),
        ),
        migrations.AlterField(
            model_name='card',
            name='img',
            field=models.ImageField(blank=True, upload_to='card_img'),
        ),
        migrations.AlterField(
            model_name='character',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Мертв'), (1, 'Жив'), (2, 'Вихт')], default=1),
        ),
    ]
