# Generated by Django 2.0.7 on 2019-04-24 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190424_0832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Вихт'), (1, 'Жив'), (0, 'Мертв')], default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
