# Generated by Django 2.0.7 on 2019-04-24 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190424_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Мертв'), (2, 'Вихт'), (1, 'Жив')], default=1),
        ),
    ]
