# Generated by Django 2.0.7 on 2019-04-24 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_auto_20190424_0916'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDevices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device_id', models.CharField(blank=True, max_length=200, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='question',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='series',
            name='number',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='f', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='l', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='series',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Скоро будет'), (0, 'Вышла')], default=1),
        ),
        migrations.AddField(
            model_name='userdevices',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
